namespace PinePhoneCore.Enums
{
    public enum TouchGesture
    {
        None = -1,
        SwipeLeft =0,
        SwipeRight = 1,
        SwipeUp =2,
        SwipeDown =3,
        SwipeUpLeft = 4,
        SwipeUpRight = 5,
        SwipeDownRight = 6,
        SwipeDownLeft = 7,
        TopEdgeSwipeLeft = 8,
        TopEdgeSwipeUp = 9,
        TopEdgeSwipeRight = 10,
        TopEdgeSwipeDown = 11,
        TopEdgeSwipeUpLeft = 12,
        TopEdgeSwipeUpRight = 13,
        TopEdgeSwipeDownRight = 14,
        TopEdgeSwipeDownLeft = 15,
        RightEdgeSwipeLeft = 16,
        RightEdgeSwipeUp = 17,
        RightEdgeSwipeRight = 18,
        RightEdgeSwipeDown = 19,
        RightEdgeSwipeUpLeft = 20,
        RightEdgeSwipeUpRight = 21,
        RightEdgeSwipeDownRight = 22,
        RightEdgeSwipeDownLeft = 23,
        BottomEdgeSwipeLeft = 24,
        BottomEdgeSwipeUp = 25,
        BottomEdgeSwipeRight = 26,
        BottomEdgeSwipeDown = 27,
        BottomEdgeSwipeUpLeft = 28,
        BottomEdgeSwipeUpRight = 29,
        BottomEdgeSwipeDownRight = 30,
        BottomEdgeSwipeDownLeft = 31,
        LeftEdgeSwipeLeft = 32,
        LeftEdgeSwipeUp = 33,
        LeftEdgeSwipeRight = 34,
        LeftEdgeSwipeDown = 35,
        LeftEdgeSwipeUpLeft = 36,
        LeftEdgeSwipeUpRight = 37,
        LeftEdgeSwipeDownRight = 38,
        LeftEdgeSwipeDownLeft = 39,
    }
}
