#!/usr/bin/env sh

export USER=alarm
export BROWSER=/usr/bin/chromium
export EDITOR=/usr/bin/micro

#export SXMO_RTCWAKEINTERVAL=3600
export SXMO_LOCK_SCREEN_OFF=1

xset dpms
xset s 60 60

dotnet ~/coding/ppjackd/bin/Debug/net6.0/ppjackd.dll > ~/ppjackd.log &

conky -d -c ~/.config/sxmo/conky.conf
feh --bg-fill ~/.bg
~/.local/bin/audioctl.sh s 50
