#!/usr/bin/env sh

# This script is executed (asynchronously) when you pick up an incoming call

# kill existing ring playback
MPVID="$(cat "$XDG_RUNTIME_DIR/sxmo.ring.pid")"
kill $MPVID
rm "$XDG_RUNTIME_DIR/sxmo.ring.pid"